//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bludata.Library.Resource {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bludata.Library.Resource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar.
        /// </summary>
        public static string btn_Alterar {
            get {
                return ResourceManager.GetString("btn_Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar.
        /// </summary>
        public static string btn_Cadastrar {
            get {
                return ResourceManager.GetString("btn_Cadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deletar.
        /// </summary>
        public static string btn_Deletar {
            get {
                return ResourceManager.GetString("btn_Deletar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não.
        /// </summary>
        public static string btn_Nao {
            get {
                return ResourceManager.GetString("btn_Nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sim.
        /// </summary>
        public static string btn_Sim {
            get {
                return ResourceManager.GetString("btn_Sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Voltar.
        /// </summary>
        public static string btn_Voltar {
            get {
                return ResourceManager.GetString("btn_Voltar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF.
        /// </summary>
        public static string CPF {
            get {
                return ResourceManager.GetString("CPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de cadastro.
        /// </summary>
        public static string DataCadastro {
            get {
                return ResourceManager.GetString("DataCadastro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data de nascimento.
        /// </summary>
        public static string DataNascimento {
            get {
                return ResourceManager.GetString("DataNascimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Anterior.
        /// </summary>
        public static string dataTables_Anterior {
            get {
                return ResourceManager.GetString("dataTables_Anterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a (filtrado de _MAX_ registros no total.).
        /// </summary>
        public static string dataTables_FiltrandoRegistrosTotal {
            get {
                return ResourceManager.GetString("dataTables_FiltrandoRegistrosTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mostrando _MENU_ registros por página.
        /// </summary>
        public static string dataTables_MostrandoRegistrosPorPagina {
            get {
                return ResourceManager.GetString("dataTables_MostrandoRegistrosPorPagina", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro disponível.
        /// </summary>
        public static string dataTables_NenhumRegistroDisponivel {
            get {
                return ResourceManager.GetString("dataTables_NenhumRegistroDisponivel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhum registro encontrado.
        /// </summary>
        public static string dataTables_NenhumRegistroEncontrado {
            get {
                return ResourceManager.GetString("dataTables_NenhumRegistroEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Página _PAGE_ de _PAGES_.
        /// </summary>
        public static string dataTables_PaginaDe {
            get {
                return ResourceManager.GetString("dataTables_PaginaDe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Primeira.
        /// </summary>
        public static string dataTables_Primeira {
            get {
                return ResourceManager.GetString("dataTables_Primeira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Procurar:.
        /// </summary>
        public static string dataTables_Procurar {
            get {
                return ResourceManager.GetString("dataTables_Procurar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Próxima.
        /// </summary>
        public static string dataTables_Proxima {
            get {
                return ResourceManager.GetString("dataTables_Proxima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Última.
        /// </summary>
        public static string dataTables_Ultima {
            get {
                return ResourceManager.GetString("dataTables_Ultima", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Alterar.
        /// </summary>
        public static string lbl_Alterar {
            get {
                return ResourceManager.GetString("lbl_Alterar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Bludata Avaliação.
        /// </summary>
        public static string lbl_BludataAvaliacao {
            get {
                return ResourceManager.GetString("lbl_BludataAvaliacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cadastrar.
        /// </summary>
        public static string lbl_Cadastrar {
            get {
                return ResourceManager.GetString("lbl_Cadastrar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Criado em 2017 - Marlon Luft Salvador.
        /// </summary>
        public static string lbl_CriadoEm {
            get {
                return ResourceManager.GetString("lbl_CriadoEm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Deletar Pessoa.
        /// </summary>
        public static string lbl_DeletarPessoa {
            get {
                return ResourceManager.GetString("lbl_DeletarPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro.
        /// </summary>
        public static string lbl_Erro {
            get {
                return ResourceManager.GetString("lbl_Erro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa.
        /// </summary>
        public static string lbl_Pessoa {
            get {
                return ResourceManager.GetString("lbl_Pessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoas.
        /// </summary>
        public static string lbl_Pessoas {
            get {
                return ResourceManager.GetString("lbl_Pessoas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a PR.
        /// </summary>
        public static string lbl_PR {
            get {
                return ResourceManager.GetString("lbl_PR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a SC.
        /// </summary>
        public static string lbl_SC {
            get {
                return ResourceManager.GetString("lbl_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione a sua unidade federativa.
        /// </summary>
        public static string lbl_SelecioneSuaUnidadeFederativa {
            get {
                return ResourceManager.GetString("lbl_SelecioneSuaUnidadeFederativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você realmente deseja deletar esta pessoa?.
        /// </summary>
        public static string lbl_VoceRealmenteDesejaDeletarEstaPessoa {
            get {
                return ResourceManager.GetString("lbl_VoceRealmenteDesejaDeletarEstaPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mudar Unidade Federativa.
        /// </summary>
        public static string Menu_MudarUnidadeFederativa {
            get {
                return ResourceManager.GetString("Menu_MudarUnidadeFederativa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo CPF é obrigatório.
        /// </summary>
        public static string Msg_CPFObrigatorio {
            get {
                return ResourceManager.GetString("Msg_CPFObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a A data informada é inválida..
        /// </summary>
        public static string Msg_DataInvalida {
            get {
                return ResourceManager.GetString("Msg_DataInvalida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Data de nascimento é obrigatório.
        /// </summary>
        public static string Msg_DataNascimentoObrigatorio {
            get {
                return ResourceManager.GetString("Msg_DataNascimentoObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve um erro ao processar a sua solicitação. Erro: {0}.
        /// </summary>
        public static string Msg_ErroException {
            get {
                return ResourceManager.GetString("Msg_ErroException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Falha ao deletar a pessoa. Erro: {0}.
        /// </summary>
        public static string Msg_FalhaAoDeletarAPessoa {
            get {
                return ResourceManager.GetString("Msg_FalhaAoDeletarAPessoa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Favor Adicionar ao menos um telefone..
        /// </summary>
        public static string Msg_FavorAdicionarAoMenosUmTelefone {
            get {
                return ResourceManager.GetString("Msg_FavorAdicionarAoMenosUmTelefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve um problema ao processar sua solicitação, tente novamente..
        /// </summary>
        public static string Msg_HouveUmProblemaAoProcessarSuaSolicitacao {
            get {
                return ResourceManager.GetString("Msg_HouveUmProblemaAoProcessarSuaSolicitacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não é permitido cadastrar uma pessoa com idade inferior a 18 na unidade federativa de PR..
        /// </summary>
        public static string Msg_NaoPermitidoCadastrarPessoaIdadeInferiorDezoito {
            get {
                return ResourceManager.GetString("Msg_NaoPermitidoCadastrarPessoaIdadeInferiorDezoito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nenhuma pessoa encontrada conforme Id informado..
        /// </summary>
        public static string Msg_NenhumaPessoaEncotradaConformeIdEncontrado {
            get {
                return ResourceManager.GetString("Msg_NenhumaPessoaEncotradaConformeIdEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Nome é obrigatório.
        /// </summary>
        public static string Msg_NomeObrigatorio {
            get {
                return ResourceManager.GetString("Msg_NomeObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limite de 2 a 50 caracteres..
        /// </summary>
        public static string Msg_NomeTamanho {
            get {
                return ResourceManager.GetString("Msg_NomeTamanho", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a É obrigatório informar o RG na unidade federativa de SC..
        /// </summary>
        public static string Msg_ObrigatorioInformaRGUnidadeFederativaSC {
            get {
                return ResourceManager.GetString("Msg_ObrigatorioInformaRGUnidadeFederativaSC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os dados recebidos pelos servidor estão vazios..
        /// </summary>
        public static string Msg_OsDadosRecebidosPeloServidorEstaoVazios {
            get {
                return ResourceManager.GetString("Msg_OsDadosRecebidosPeloServidorEstaoVazios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pessoa deletada com sucesso..
        /// </summary>
        public static string Msg_PessoaDeletadaComSucesso {
            get {
                return ResourceManager.GetString("Msg_PessoaDeletadaComSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tamanho máximo de 15 caracteres.
        /// </summary>
        public static string Msg_TamanhoMaximo {
            get {
                return ResourceManager.GetString("Msg_TamanhoMaximo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Campo Telefone é obrigatório.
        /// </summary>
        public static string Msg_TelefoneObrigatorio {
            get {
                return ResourceManager.GetString("Msg_TelefoneObrigatorio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a RG.
        /// </summary>
        public static string RG {
            get {
                return ResourceManager.GetString("RG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Telefone(s).
        /// </summary>
        public static string Telefone {
            get {
                return ResourceManager.GetString("Telefone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionar.
        /// </summary>
        public static string title_Adicionar {
            get {
                return ResourceManager.GetString("title_Adicionar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Remover.
        /// </summary>
        public static string title_Remover {
            get {
                return ResourceManager.GetString("title_Remover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a UF.
        /// </summary>
        public static string UF {
            get {
                return ResourceManager.GetString("UF", resourceCulture);
            }
        }
    }
}
